document.writeln("<header id=\"header\">      ");
document.writeln("        <div class=\"container\">");
document.writeln("            <div class=\"row\">");
document.writeln("                <div class=\"col-sm-12 overflow\">");
document.writeln("                   <div class=\"social-icons pull-right\">");
document.writeln("                        <ul class=\"nav nav-pills\">");
document.writeln("                            <li><a href=\"\"><i class=\"fa fa-facebook\"></i></a></li>");
document.writeln("                            <li><a href=\"\"><i class=\"fa fa-twitter\"></i></a></li>");
document.writeln("                            <li><a href=\"\"><i class=\"fa fa-google-plus\"></i></a></li>");
document.writeln("                            <li><a href=\"\"><i class=\"fa fa-dribbble\"></i></a></li>");
document.writeln("                            <li><a href=\"\"><i class=\"fa fa-linkedin\"></i></a></li>");
document.writeln("                        </ul>");
document.writeln("                    </div> ");
document.writeln("                </div>");
document.writeln("             </div>");
document.writeln("        </div>");
document.writeln("        <div class=\"navbar navbar-inverse\" role=\"banner\">");
document.writeln("            <div class=\"container\">");
document.writeln("                <div class=\"navbar-header\">");
document.writeln("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">");
document.writeln("                        <span class=\"sr-only\">Toggle navigation</span>");
document.writeln("                        <span class=\"icon-bar\"></span>");
document.writeln("                        <span class=\"icon-bar\"></span>");
document.writeln("                        <span class=\"icon-bar\"></span>");
document.writeln("                    </button>");
document.writeln("");
document.writeln("                    <a class=\"navbar-brand\" href=\"index.html\">");
document.writeln("                    	<h1><img src=\"images/logo.png\" alt=\"logo\"></h1>");
document.writeln("                    </a>");
document.writeln("                    ");
document.writeln("                </div>");
document.writeln("                <div class=\"collapse navbar-collapse\">");
document.writeln("                    <ul class=\"nav navbar-nav navbar-right\">");
document.writeln("                        <li class=\"active\"><a href=\"index.html\">主页</a></li>");
document.writeln("                        <li><a href=\"godlibrary.html\">GodLibrary</a></li>");
document.writeln("                        <li class=\"dropdown\"><a href=\"#\">Pages <i class=\"fa fa-angle-down\"></i></a>");
document.writeln("                            <ul role=\"menu\" class=\"sub-menu\">");
document.writeln("                                <li><a href=\"aboutus.html\">About</a></li>");
document.writeln("                                <li><a href=\"aboutus2.html\">About 2</a></li>");
document.writeln("                                <li><a href=\"service.html\">Services</a></li>");
document.writeln("                                <li><a href=\"pricing.html\">Pricing</a></li>");
document.writeln("                                <li><a href=\"contact.html\">Contact us</a></li>");
document.writeln("                                <li><a href=\"contact2.html\">Contact us 2</a></li>");
document.writeln("                                <li><a href=\"404.html\">404 error</a></li>");
document.writeln("                                <li><a href=\"coming-soon.html\">Coming Soon</a></li>");
document.writeln("                            </ul>");
document.writeln("                        </li>                    ");
document.writeln("                        <li class=\"dropdown\"><a href=\"blog.html\">Blog <i class=\"fa fa-angle-down\"></i></a>");
document.writeln("                            <ul role=\"menu\" class=\"sub-menu\">");
document.writeln("                                <li><a href=\"blog.html\">Blog Default</a></li>");
document.writeln("                                <li><a href=\"blogtwo.html\">Timeline Blog</a></li>");
document.writeln("                                <li><a href=\"blogone.html\">2 Columns + Right Sidebar</a></li>");
document.writeln("                                <li><a href=\"blogthree.html\">1 Column + Left Sidebar</a></li>");
document.writeln("                                <li><a href=\"blogfour.html\">Blog Masonary</a></li>");
document.writeln("                                <li><a href=\"blogdetails.html\">Blog Details</a></li>");
document.writeln("                            </ul>");
document.writeln("                        </li>");
document.writeln("                        <li class=\"dropdown\"><a href=\"portfolio.html\">Portfolio <i class=\"fa fa-angle-down\"></i></a>");
document.writeln("                            <ul role=\"menu\" class=\"sub-menu\">");
document.writeln("                                <li><a href=\"portfolio.html\">Portfolio Default</a></li>");
document.writeln("                                <li><a href=\"portfoliofour.html\">Isotope 3 Columns + Right Sidebar</a></li>");
document.writeln("                                <li><a href=\"portfolioone.html\">3 Columns + Right Sidebar</a></li>");
document.writeln("                                <li><a href=\"portfoliotwo.html\">3 Columns + Left Sidebar</a></li>");
document.writeln("                                <li><a href=\"portfoliothree.html\">2 Columns</a></li>");
document.writeln("                                <li><a href=\"portfolio-details.html\">Portfolio Details</a></li>");
document.writeln("                            </ul>");
document.writeln("                        </li>                         ");
document.writeln("                                           ");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\"search\">");
document.writeln("                    <form role=\"form\">");
document.writeln("                        <i class=\"fa fa-search\"></i>");
document.writeln("                        <div class=\"field-toggle\">");
document.writeln("                            <input type=\"text\" class=\"search-form\" autocomplete=\"off\" placeholder=\"Search\">");
document.writeln("                        </div>");
document.writeln("                    </form>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </header>");