document.writeln("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
document.writeln("    <meta name=\"description\" content=\"\">");
document.writeln("    <meta name=\"author\" content=\"\">");
document.writeln("    <title>Home | Triangle</title>");
document.writeln("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">");
document.writeln("    <link href=\"css/font-awesome.min.css\" rel=\"stylesheet\">");
document.writeln("    <link href=\"css/animate.min.css\" rel=\"stylesheet\"> ");
document.writeln("    <link href=\"css/lightbox.css\" rel=\"stylesheet\"> ");
document.writeln("	<link href=\"css/main.css\" rel=\"stylesheet\">");
document.writeln("	<link href=\"css/responsive.css\" rel=\"stylesheet\">");
document.writeln("    <!--[if lt IE 9]>");
document.writeln("	    <script src=\"js/html5shiv.js\"></script>");
document.writeln("	    <script src=\"js/respond.min.js\"></script>");
document.writeln("    <![endif]-->       ");
document.writeln("    <link rel=\"shortcut icon\" href=\"images/ico/favicon.ico\">");
document.writeln("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"images/ico/apple-touch-icon-144-precomposed.png\">");
document.writeln("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"images/ico/apple-touch-icon-114-precomposed.png\">");
document.writeln("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"images/ico/apple-touch-icon-72-precomposed.png\">");
document.writeln("    <link rel=\"apple-touch-icon-precomposed\" href=\"images/ico/apple-touch-icon-57-precomposed.png\">");